name = "scTransformer"
uuid = "6768ce78-dd5b-4160-b677-5994b15e298d"
authors = ["Yueh-Hua Tu"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
